apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2019-09-24T15:22:08Z
  labels:
    app: hello
  name: hello
  namespace: smoke-test
  resourceVersion: "221244"
  selfLink: /api/v1/namespaces/smoke-test/services/hello
  uid: 12aca75c-dedf-11e9-a62e-5254008afee6
spec:
  clusterIP: 172.30.229.234
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: hello
    deploymentconfig: hello
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
